config/routes.rb
Rails.application.routes.draw do

  root 'desserts#index'
  get '/desserts' => 'desserts#index'
  get '/desserts/favorite' => 'desserts#favorite', as: :favorite_dessert
  get '/desserts/:id' => 'desserts#show', as: :show_dessert
  post '/desserts/:id/save_as_favorite' => 'desserts#save_as_favorite', as: :save_as_favorite

end

app/models/cookie.rb
class Cookie

  attr_reader :img_url, :id


  def initialize(args={})
    @id = args[:id]
    @img_url = args[:img_url]
  end

  @@all = [
      Cookie.new({id: "1", img_url: "http://i.imgur.com/irvtyXG.gif"}),
      Cookie.new({id: "2", img_url: "http://i.imgur.com/pB4MEQP.jpg"}),
      Cookie.new({id: "3", img_url: "http://i.imgur.com/RbdlzzL.jpg"})
  ]

  def self.all
    @@all
  end

  def self.find(id)
    all.find {|c| c.id == id.to_s }
  end

end

app/models/dessert.rb
class Dessert

  attr_reader :img_url, :id


  def initialize(args={})
    @id = args[:id]
    @img_url = args[:img_url]
  end

  @@all = [
      Dessert.new({id: "1", img_url: "http://i.imgur.com/irvtyXG.gif"}),
      Dessert.new({id: "2", img_url: "http://i.imgur.com/pB4MEQP.jpg"}),
      Dessert.new({id: "3", img_url: "http://i.imgur.com/RbdlzzL.jpg"})
  ]

  def self.all
    @@all
  end

  def self.find(id)
    all.find {|c| c.id == id.to_s }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize
    redirect_to root_path and return if not is_logged_in
  end

  def is_logged_in
    cookies[:can_access] == "yes"
  end
end

app/controllers/desserts_controller.rb
class DessertsController < ApplicationController

  # GET /desserts
  def index
    @desserts = Dessert.all
  end

  # GET /desserts/1
  def show
    redirect_to root_path and return if not is_logged_in

    ## CHALLENGE 4: This is my favorite dessert!
    ### Detect whether the dessert the user is viewing
    ### is their favorite_dessert, and add the words
    ### 'FAVORITE dessert' in the `views/desserts/show.html.erb` template
    @dessert = Dessert.find(params[:id])
    if session[:favorite_dessert_id] == params[:id]
      @message = "FAVORITE dessert"
    end
  end

  # GET /desserts/favorite
  # Shows the user's favorite dessert (if set in the session)
  def favorite
    redirect_to root_path and return if not is_logged_in

    ## CHALLENGE 3: Render my favorite_dessert!
    ### Check my session for my `favorite_dessert_id`
    ### and then render my favorite dessert
    ### AS-IS this will raise an error
    favorite_dessert_id = session[:favorite_dessert_id]
    @dessert = Dessert.find(favorite_dessert_id)
    render 'show'
  end

  # POST /desserts/1/save_as_favorite
  # Sets the user's favorite dessert in their session
  def save_as_favorite
    redirect_to root_path and return if not is_logged_in
    session[:favorite_dessert_id] = params[:id] # SET favorite
    flash[:notice] = "dessert #{params[:id]} saved in session as favorite!"
    redirect_to root_path
  end

  private

  def is_logged_in
    cookies[:can_access] == "yes"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desserts_helper.rb
module DessertsHelper
end

app/views/deserts/show.html.erb
<p id="notice"><%= notice %></p>

<p> You can see this image because you set the cookie `can_has` equal to `yarly` in your browser. Otherwise the server would have redirected you back to the homepage.</p>

<%= image_tag @desert.img_url %>

</br>

<!-- CHANGE THIS link to reflect whether the desert has already been favorited -->
<%= button_to "Save as Favorite", save_as_favorite_path(@desert.id) %>

app/views/desserts/index.html.erb
<div id="desserts_index_page">
  <p id="notice"><%= notice %></p>

  <h1>Hack the desserts!</h1>
    <%= link_to "Go to your Favorite dessert", favorite_dessert_path %>


  <ul>
    <% @desserts.each do |dessert| %>
      <li>
        <%= link_to "Show dessert #{dessert.id}", show_dessert_path(dessert.id) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/desserts/show.html.erb
<p id="notice"><%= notice %></p>

<p> You can see this image because you set the cookie `can_access` equal to `yes` in your browser. Otherwise the server would have redirected you back to the homepage.</p>

<%= image_tag @dessert.img_url %>

</br>

<%= @message %>


<!-- CHANGE THIS link to reflect whether the dessert has already been favorited -->
<%= button_to "Save as Favorite", save_as_favorite_path(@dessert.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookieMonsterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>